### PR TITLE
Update for Xcode 10.2 / Swift 5

### PR DESCRIPTION
**Pull request by weakfl**
- bump version to `5.0.0`
 - add swift version to podspec
 - remove file `.swift-version` (deprecated)
 - update project to recommended settings
 - update RSKPlaceholderTextViewExample

```
$ pod lib lint

 -> RSKPlaceholderTextView (4.0.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description

RSKPlaceholderTextView passed validation.
```

**NOTES:**
- still needs to be tagged and pushed to cocoapods obviously
- `@unknown default` case for `UIUserInterfaceLayoutDirection` will cause an `assertionFailure(_:)` (see [here](https://github.com/weakfl/RSKPlaceholderTextView/blob/8e91639701fb351023d8780f509eba3f875a348d/RSKPlaceholderTextView/RSKPlaceholderTextView.swift#L221-L223))

### CODE REVIEW

**Comment by ruslanskorb** [comment]
@weakfl Hi,

Thanks for the PR!

- Could you rebase your changes onto the master branch?
- Also, I prefer to stay with `.swift-version` file. It is still useful for [`swiftenv`](https://github.com/kylef/swiftenv). Could you restore this file?
- Instead of `assertionFailure(_:)` for `@unknown default` case lets use the same calculations as for `leftToRight` case.
```swift
switch userInterfaceLayoutDirection {
    
case .rightToLeft:
    caretRect.origin.x = placeholderUsedRect.maxX - self.placeholderInsets.left
    
case .leftToRight:
    fallthrough
    
@unknown default:
    caretRect.origin.x = placeholderUsedRect.minX + self.placeholderInsets.left
}
```

**Comment by weakfl** [comment]
@ruslanskorb done

**Comment by ruslanskorb** [comment]
@weakfl Thank you!

**Comment by weakfl** [comment]
@ruslanskorb Can you please push the new release to cocoapods? Thanks ;)

**Comment by ruslanskorb** [comment]
@weakfl Already pushed - https://github.com/CocoaPods/Specs/blob/master/Specs/7/0/2/RSKPlaceholderTextView/5.0.0/RSKPlaceholderTextView.podspec.json

**Comment by weakfl** [comment]
@ruslanskorb Thanks, probably just needs some time before it's available...

**Comment by ruslanskorb** [comment]
@weakfl Have you tried `pod install --repo-update`?

**Comment by weakfl** [comment]
@ruslanskorb thanks, it's already available, although cocoapods.org is still listing version `4.0.0`.

**Pull request merged**
